git clone https://bitbucket.org/emetra/bar.git BAR
git clone https://bitbucket.org/emetra/barneovervekt.git BARNEOVERVEKT
git clone https://bitbucket.org/emetra/cts.git CTS
git clone https://bitbucket.org/emetra/endo.git ENDO
git clone https://bitbucket.org/emetra/fettvest.git FettVest
git clone https://bitbucket.org/emetra/gbd.git GBD
git clone https://bitbucket.org/emetra/hand.git HAND
git clone https://bitbucket.org/emetra/hofte.git HOFTE
git clone https://bitbucket.org/emetra/langtid.git LANGTID
git clone https://bitbucket.org/emetra/lipid.git LIPID
git clone https://bitbucket.org/emetra/ndv.git NDV
git clone https://bitbucket.org/emetra/overvekt.git OVERVEKT
git clone https://bitbucket.org/emetra/pfo.git PFO
git clone https://bitbucket.org/emetra/roas.git ROAS
git clone https://bitbucket.org/emetra/slag.git SLAG
rem git clone https://bitbucket.org/emetra/soreg.git SOREG
git clone https://bitbucket.org/emetra/ultradian.git Ultradian
git clone https://bitbucket.org/emetra/vossbar.git VOSSBAR
git clone https://bitbucket.org/emetra/vrex.git VREX