SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION UpgradeTo6018
PRINT 'Starting upgrade to 6018'

DELETE FROM DbUpgradeLog WHERE DbVer > 6017;

EXEC DbCheckVersion 6017;
EXECUTE DbStartUpgrade 6018;
GO

IF dbo.DbColumnExists( 'MetaStudyForm','FormTitle' ) = 0
BEGIN
  ALTER TABLE dbo.MetaStudyForm ADD FormTitle VARCHAR(128) NULL
  UPDATE dbo.MetaStudyForm SET LastUpdate = '2000-01-01'
END
GO

EXECUTE dbo.DbFinalizeUpgrade 6018;
GO

COMMIT TRANSACTION UpgradeTo6018;
GO