SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION UpgradeTo6016
PRINT 'Starting upgrade to 6016'

DELETE FROM DbUpgradeLog WHERE DbVer > 6015;

EXEC DbCheckVersion 6015;
EXECUTE DbStartUpgrade 6016;
GO

DELETE FROM dbo.MetaFormItem WHERE FormItemId IN ( 2203,2973)
GO

ALTER TABLE dbo.MetaFormItem DROP CONSTRAINT FK_MetaFormItem_PageId
GO

ALTER TABLE dbo.MetaFormItem WITH CHECK ADD CONSTRAINT FK_MetaFormItem_PageId FOREIGN KEY (PageId)
  REFERENCES dbo.MetaFormPage (PageId)
  ON DELETE CASCADE
  ON UPDATE NO ACTION
GO

IF EXISTS ( SELECT id FROM sysobjects WHERE name='FK_MetaFormItem_ItemId' ) 
  ALTER TABLE dbo.MetaFormItem DROP CONSTRAINT FK_MetaFormItem_ItemId
GO

ALTER TABLE dbo.MetaFormItem ADD CONSTRAINT FK_MetaFormItem_ItemId FOREIGN KEY (ItemId)
  REFERENCES dbo.MetaItem(ItemId)
  ON DELETE CASCADE
  ON UPDATE NO ACTION
GO

IF EXISTS ( SELECT id FROM sysobjects WHERE name='FK_MetaFormItem_FormId' ) 
  ALTER TABLE dbo.MetaFormItem DROP CONSTRAINT FK_MetaFormItem_FormId
GO

ALTER TABLE dbo.MetaFormItem ADD CONSTRAINT FK_MetaFormItem_FormId FOREIGN KEY (FormId)
  REFERENCES dbo.MetaForm(FormId)
  ON DELETE CASCADE
  ON UPDATE NO ACTION
GO

EXECUTE dbo.DbFinalizeUpgrade 6016;
GO

COMMIT TRANSACTION UpgradeTo6016;
GO
